### ISSUE TITLE
Feature request: orion_node_facts

### ISSUE THREAD

**Issue by smatterchew** [ashleyghooper/solarwinds_ansible#3]
I would like the ability to search for one or more nodes based on criteria in the node record.  

Interesting searches would be:
- All nodes running an OS and a polling type (e.g., Linux and SNMPv3).  This can be really broad.  If I search for SERVERS running Linux and SNMPv3, I would need to not get back things like Power Distribution Units with an embedded Linux OS.
- All nodes with a name containing a string (e.g., everything in the `foo.bar` domain)
- All nodes with a string at the beginning of a name (e.g., everything whose name begins with `baz*`)
- All nodes in an IPv4 address range
- All nodes whose custom property named Region equal to EMEA

I don't think it should be a failure to return a list of zero nodes.
The returned data should be searchable via `json_query`.

**Comment by ashleyghooper** [comment]
Thanks for this one too. This is another one that's on the roadmap. I was leaning more towards naming it `orion_node_info` but maybe `_facts` is better.

In the meantime, I was able to get the particular functionality I required, which was the ability to check if a node already existed in SolarWinds, by calling the `orion_node` module with `state=present` and `check_mode=yes`.

There's also the possibility of an inventory plugin at some point.

**Comment by ashleyghooper** [comment]
> I was leaning more towards naming it `orion_node_info` but maybe `_facts` is better.

Actually, it [appears](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module) that `orion_node_info` is likely a better name for what I think you are describing.

> Only use ansible_facts for information that is specific to the host machine, for example network interfaces and their configuration, which operating system and which programs are installed.
> Modules that query/return general information (and not ansible_facts) should be named _info. General information is non-host specific information, for example information on online/cloud services (you can access different accounts for the same online service from the same host), or information on VMs and containers accessible from the machine, or information on individual files or programs.

**Comment by smatterchew** [comment]
I'm OK either way.  I used _facts, because these are configuration facts specific to one host. Argument can be made against that though because they aren't facts the host provides.  Aren't intrinsic to the host.

**Comment by ashleyghooper** [comment]
Hi @smatterchew, I've pushed `orion_node_info` to the `feature-node-info` branch of this repo. Let me know if you're not sure how to install it from this repo so that you can use it.

**Please read the docs, especially regarding the use of wildcards.**

I've done a fair amount of testing of it, but am keen to hear how it works for you.

Unfortunately, determining the OS type is not easy [1]. I think it's going to be down to individual sites to work out how they use the data that `orion_node_info` provides based on what devices they have in their environment, how they're polled, etc.

[1] https://thwack.solarwinds.com/product-forums/server-application-monitor-sam/f/forum/53692/finding-out-windows-server-editions-standard-enterprise-datacenter

**Comment by smatterchew** [comment]
Thanks @ashleyghooper.  I was able to get this branch working.  

I like that the module always returns a `results` list and that it can be zero records long.  Makes implementation much easier.

Some questions/observations.

1. Along with `failed`, `changed`, and `results` can you provide a `count` of records coming back?
2. Can I limit the returned fields to a list of fields I provide?  For instance, just the NodeID?  Expectation is that this would lower the pressure on the backend.  Also, return zero fields, just the count?
3. Can you provide an example of how to select all nodes where `ObjectSubType` is SNMP and `SNMPVersion` is not 3?
4. I made a call that had no criteria expecting to get a return of all nodes and it failed. `"Nodes query failed: 400 Client Error: no viable alternative at input '<EOF>' in Where clause for url: ...`
5. Do you have any thoughts on batching or pagination for when the list of responsive node records is excessive?  Does Orion even support this type of interaction?

Also, it might help some of us not familiar with the query language to see the query you are building.  Can that be added to the output?

**Comment by ashleyghooper** [comment]
Hi @smatterchew,

thanks for the feedback.

>     1. Along with `failed`, `changed`, and `results` can you provide a `count` of records coming back?

Would it suffice to use `my_var.results | length`?

>     2. Can I limit the returned fields to a list of fields I provide?  For instance, just the NodeID?  Expectation is that this would lower the pressure on the backend.  Also, return zero fields, just the count?

Although it won't reduce load on the SWIS, `my_var.results | map(attribute='NodeID') | list` will achieve the former, and `my_var.results | length` the latter. I did consider restriction of fields but hadn't decided on it - I lean towards the Unix philosophy, so I'm keen to use what Ansible/Jinja already provide where possible, rather than increasing complexity of the code. Having said that, if the consumer is only interested in e.g. `NodeID`, then we could skip retrieving  agent info and custom properties for each matched node, so I'm considering something like this.
 
>     3. Can you provide an example of how to select all nodes where `ObjectSubType` is SNMP and `SNMPVersion` is not 3?

An example would be as below, but I fear that's not what you meant and I think what you're getting at is negative filters (à la SQL `NOT`), which the current module doesn't support. I'd like to research a few other `info` modules and see if/how they've attacked this.

```yaml
  object_sub_type: snmp
  snmp_version:
    - 1
    - 2
```

>     4. I made a call that had no criteria expecting to get a return of all nodes and it failed. `"Nodes query failed: 400 Client Error: no viable alternative at input '<EOF>' in Where clause for url: ...`

Thanks for catching that one. I've pushed a fix for it, making the addition of the WHERE clause conditional on there being some criteria to filter on.

>     5. Do you have any thoughts on batching or pagination for when the list of responsive node records is excessive?  Does Orion even support this type of interaction?
> Also, it might help some of us not familiar with the query language to see the query you are building. Can that be added to the output?

This should be possible by way of e.g. `WITH ROWS 1 TO 50`. In order to accommodate these and some other of your suggestions, I'm thinking that the filters should probably be nested below a key named `filters`, allowing placement of other options like e.g. `debug`, `fields`, `show_query`, etc alongside it. This would of course be a breaking change.

Thanks again for the feedback and useful suggestions for improvements.

**Comment by smatterchew** [comment]
Hi @ashleyghooper.  Thanks for the quick responses.

Yes, `my_var.results|length` will work if all records are returned at one time.  If pagination/batching is implemented though, this would be a good way to let the user know that there are more records than `my_var.results|length` records.  Our Orion implementation has well over 6k node records for servers alone.  Currently working on a dev instance of Orion, but I can see that at least one of my use cases will return over 600 records.  I hate batching/pagination in Ansible, but there might be a need if I can't get very specific with my query.

Yes, I am referring to a negative filter in the query.  The benefit is that I don't need to know what the value **could** be.

On the issue of pre-filtering the results at the SWIS end, if the product doesn't support it, I don't need it.  I'm just trying to conserve compute and bandwidth if the full complement of fields is not needed.

Thanks for considering the `filters` request.  That feature in other modules/technologies is immensely helpful to me to understand how things work.

**Comment by smatterchew** [comment]
> In the meantime, I was able to get the particular functionality I required, which was the ability to check if a node already existed in SolarWinds, by calling the `orion_node` module with `state=present` and `check_mode=yes`.

Hi @ashleyghooper.  I was able to use the `orion_node` module with `state: present` and `check_mode: true` to return info about the node.  Thank you for this.  
> 
> There's also the possibility of an inventory plugin at some point.

If it helps your planning, this is not a high priority for us.

Also, when you create the node, can you return the `uri` to the node as well?  I intend to close a ServiceNow server build request->Monitoring task with the URI in the notes field as part of the build documentation process.  Returning it during creation will prevent another call.

Really good work here.  Thank you for your efforts.

**Comment by ashleyghooper** [comment]
Hello,
I've just pushed a new branch `feature-solarwinds-info` where I've taken querying the SWIS in quite a different direction to avoid impractical amounts of hard coding that would be necessary for the functionality requested.

An example playbook task is below:

```yaml
    - name: Get SolarWinds node info with interfaces
      anophelesgreyhoe.solarwinds.solarwinds_info:
        solarwinds_connection:
          hostname: "{{ orion_hostname }}"
          username: "{{ orion_username }}"
          password: "{{ orion_password }}"
        base_table: Orion.Nodes
        columns:
          Orion.Nodes:
            - NodeID
            - Caption
            - IP
            - StatusDescription
          Orion.NodesCustomProperties:
            - Country
          Orion.NPM.Interfaces:
            - Name
            - Speed
            - Bps
            - Outbps
            - Inbps
            - OutPercentUtil
            - InPercentUtil
          Orion.StatusInfo:
            - StatusName
        include:
          Orion.Nodes:
            IPAddress: "10.150.%"
          Orion.NPM.Interfaces:
            Bps:
              min: 51409.8
          Orion.StatusInfo:
            StatusName: Down
        exclude:
          Orion.NodesCustomProperties:
            Country: Australia
      delegate_to: localhost
```

Specification of entities (tables) and properties (columns) to query now follows naming in [SWIS](https://solarwinds.github.io/OrionSDK/schema/index.html), although for some tables there are shorthand names defined in the `SolarWindsEntityAlias` enum as below (let me know if there are more you'd like to add). It might be possible to enable site-local definitions of these short names later on.

```python
    Agents = "Orion.AgentManagement.Agent"
    CustomProperties = "Orion.NodesCustomProperties"
    Engines = "Orion.Engines"
    Interfaces = "Orion.NPM.Interfaces"
    Nodes = "Orion.Nodes"
    PollingEngines = "Orion.Engines"
    Volumes = "Orion.Volumes"
```

In terms of what is returned, both tables and their columns can be specified. If tables are specified without columns, then all columns are returned. If the `columns` dict is empty, then all columns for the base table only are returned, although filters defined via `include` and `exclude` will still work.

The module documentation will be helpful.

The module uses the SWIS metadata tables to work out how to join  tables, although it's oriented around using a single _base table_ and then joining other tables to that based on primary/foreign key relations. I wouldn't expect it to work with tables that join tables that in turn join other tables.

Overall it's basically working although there are potentially some other things to add as well as a bit of refactoring and optimisation.

NB: For now there is no paging of results. In my testing, I've found that some very broad queries (e.g. returning data for 6,000 or more nodes) can take 5 minutes or more (depending on which columns and nested entities are included), but use of paging e.g. `ORDER BY NodeID WITH ROWS 1 TO 50` did not seem to make any discernible difference to the time the query took to run, so I'm not sure how the marshaling of results is happening, but it didn't appear to help. I will do some more testing.

Please try it when you can and let me know how it works for you.

**Comment by ashleyghooper** [comment]
> Also, return zero fields, just the count?

The module output now includes the count and also all of the queries it ran, but for now there's no way to return zero fields in the `data` element of the output dict, so I'd recommend just specifying a single column in the base table (e.g. `NodeID`) to conserve resources.

**Comment by ashleyghooper** [comment]
Actually, hold fire on that `feature-solarwinds-info` branch.

I happened to discover soon after my previous comments that SWQL supports 'navigating' related entities using a dot notation, e.g. `SELECT NodeID, N.CustomProperties.Country FROM Orion.Nodes AS N`.

I'm reworking the `solarwinds_info` module to use that approach in the `feature-swql-features` branch, which has greatly simplified the code.

**Comment by ashleyghooper** [comment]
```yaml
    - name: Get SolarWinds node info with interfaces
      anophelesgreyhoe.solarwinds.solarwinds_info:
        solarwinds_connection:
          hostname: "{{ solarwinds_host }}"
          username: "{{ solarwinds_username }}"
          password: "{{ solarwinds_password }}"
        base_table:
          name: Orion.Nodes
          columns:
            - NodeID
            - Caption
            - IP
            - StatusDescription
        nested_entities:
          CustomProperties:
            columns:
              - Country
          Interfaces:
            columns:
              - Name
              - Speed
              - Bps
              - Outbps
              - Inbps
              - OutPercentUtil
              - InPercentUtil
        include:
          IPAddress: "10.%"
          Interfaces.Bps:
            min: 51409.8
          Status: 2
        exclude:
          CustomProperties.Country: Australia
      delegate_to: localhost
```
