### ISSUE TITLE
Feature Request: Get a list of polling engines

### ISSUE THREAD

**Issue by smatterchew** [ashleyghooper/solarwinds_ansible#5]
Hi @ashleyghooper.

The `orion_node` module has the ability to set a specific polling engine for a given node at creation time.  Can you provide a module that will return as much data about the polling engines as you can collect?  This will help in selecting and assigning an appropriate node.

Thank you

**Comment by ashleyghooper** [comment]
There's an example in the module documentation for the new `solarwinds_info` module to get all details of polling engines as below.

```yaml
    - name: Run a regular SolarWinds Information Service query
      anophelesgreyhoe.solarwinds.solarwinds_info:
        solarwinds_connection:
          hostname: "{{ orion_hostname }}"
          username: "{{ orion_username }}"
          password: "{{ orion_password }}"
        base_table: Orion.Engines
      delegate_to: localhost
```

**Comment by ashleyghooper** [comment]
For the version in the `feature-swql-features` branch, we would just need a slight modification to get polling engine details:

```yaml
    - name: Run a regular SolarWinds Information Service query
      anophelesgreyhoe.solarwinds.solarwinds_info:
        solarwinds_connection:
          hostname: "{{ orion_hostname }}"
          username: "{{ orion_username }}"
          password: "{{ orion_password }}"
        base_table:
          name: Orion.Engines
          all_columns: yes
      delegate_to: localhost
```

**Comment by smatterchew** [comment]
Thanks @ashleyghooper.

With the example above I am able to pull a list of engines.

From your example I get:
```json
    "msg": {
        "changed": false,
        "failed": false,
        "info": {
            "count": 1,
            "data": [
                {
                    "AvgCPUUtil": 0.0,
                    "BusinessLayerPort": 17777,
```
Modules from Red Hat and other projects seem to have a standard return format that looks more like this one from the [Project List API endpoint in Ansible Tower](https://docs.ansible.com/ansible-tower/2.3.0/html/towerapi/projects.html):
```json
{
    "count": 99,
    "next": null,
    "previous": null,
    "results": [
        ...
    ]
}
```
Would it be possible to have these modules follow this example for returned data structures?
```json
{
    "changed": false,
    "count": 7
    "failed": false,
    "results": [
        {
            "AvgCPUUtil": 0.0,
            "BusinessLayerPort": 17777,
```
Thank you

**Comment by smatterchew** [comment]
I need some guidance on the `column: ` arg.  When I leave it out, the module returns what I am thinking is everything about all of the polling engines.  When I try to limit the result columns to just `EngineID` using this call:
```yaml
- name: "Collect a list of polling engines"
  delegate_to: localhost
  anophelesgreyhoe.solarwinds.solarwinds_info:
    solarwinds_connection:
      hostname: "{{ orion_host }}"
      username: "{{ orion_account }}"
      password: "{{ orion_password }}"
    base_table: Orion.Engines
    columns:
      - o_e:
          - EngineID
          - MasterEngineID      
      # - "o_e.EngineID"
      # - o_e.EngineID
      # - "EngineID"
      # - EngineID
  register: orion_polling_engines
```
I get the error `FAILED! => {"changed": false, "msg": "argument 'columns' is of type <class 'list'> and we were unable to convert to dict: <class 'list'> cannot be converted to a dict"}`.

I tried the "o_e." form of the column based on your return of the select statement.  Thanks for supporting that feature.

I also tried selecting more than one column thinking that there might be a stray `,` in the select string without two columns, but it still failed.  I think I don't understand the description for the arg that you supplied: "...in the form of a dict of table names...".  

For this arg, I would expect a simple list?  Can you provide an example in the usage for the column?

**Comment by ashleyghooper** [comment]
Hi @smatterchew, it looks like you may still be using the version in branch `feature-solarwinds-info`, or at least using the syntax for that version. If so, could you switch to the `feature-swql-features` branch and syntax that I [mentioned](https://github.com/ashleyghooper/solarwinds_ansible/issues/3#issuecomment-1370568608) on issue #3 ?

Unfortunately, the syntax changes slightly with the newer version, due to the way queries are constructed to take advantage of SWQL's _navigation_ feature, which means most of the time explicit joins between related tables are not required.

So to adapt the last example I pasted above to return only a single column, it's just a case of removing the `all_columns` key under `base_table`, and replacing with a `columns` key which contains a list of columns.

```yaml
    - name: Run a regular SolarWinds Information Service query
      anophelesgreyhoe.solarwinds.solarwinds_info:
        solarwinds_connection:
          hostname: "{{ orion_hostname }}"
          username: "{{ orion_username }}"
          password: "{{ orion_password }}"
        base_table:
          name: Orion.Engines
          columns:
            - EngineID
      delegate_to: localhost
```

The last example in the `solarwinds_info.py` code uses the same approach, albeit for the `Orion.Nodes` table.
