### ISSUE TITLE
Feature Request: solarwinds_info - enable specification of multiple filters (SQL 'OR')

### ISSUE THREAD

**Issue by ashleyghooper** [ashleyghooper/solarwinds_ansible#8]
By way of the `include` and `exclude` parameters, the `solarwinds_info` module enables use of somewhat complex filtering logic, however, it's currently not capable of generating an SWQL query that includes records where *column1* has/doesn't have a particular value **or** *column2* has/doesn't have a particular value.

For example, suppose I want to get a list of nodes where:
- `Severity` > 100, or
- `Status` = 2 (down)

The below YAML snippet would match nodes that have *both* a `Severity` of 100 or greater, *and* a `Status` of 2, but excluding any where the `Country` custom property is "Australia".

```yaml
base_table: Orion.Nodes
include:
  Severity:
    min: 100
  Status: 2
exclude:
  CustomProperties.Country: Australia
```

Create a new argument `filters` which contains a *list* of filters, using the same `include`/`exclude` syntax. This enables the query as below, although note the required repetition of the `exclude` filter on `CustomProperties.Country`:

```yaml
base_table: Orion.Nodes
filters:
  - include:
      Severity:
        min: 100
    exclude:
      CustomProperties.Country: Australia
  - include:
      Status: 2
    exclude:
      CustomProperties.Country: Australia
```
